#! /bin/bash

sxhkd -c ~/.config/sxhkd/sxhkdrc &
autorandr -c & 
# Click on touchpad
xinput set-prop 11 352 1
# Natural scrolling
xinput set-prop 11 329 1

~/.config/bspwm/startup.sh

eww daemon &
dunst -conf ~/.config/dunst/dunstrc &
picom &

if [[ $(xrandr -q | grep "DP-2 connected") ]]; then
  bspc monitor eDP-1 -d 1 2 3 4 5 &
  bspc monitor DP-2 -d 6 7 8 9 0 &
else 
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0 & 
fi

bspc config border_width 3
bspc config focused_border_color "#a6e3a1"
  
bspc config window_gap 10
bspc config pointer_follows_monitor true

bspc config split_ratio 0.5
bspc rule -a Google-chrome desktop='^2' follow=on monitor="focused"
bspc rule -a Code desktop='^3' follow=on monitor="focused"
