import = ["/home/nathan/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.6"


[font]
size = 6

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "BoldItalic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "MediumItalic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Medium"

[scrolling]
history = 10000
multiplier = 4

[window]
opacity = 0.85

[window.padding]
x = 6
y = 6
